apiVersion : apps/v1
kind: Deployment
metadata:
  name: eplastapi
  labels:
    app: eplastapi  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eplastapi
  template:
    metadata:
      labels:
        app: eplastapi 
    spec:
      containers:
        - name: eplastapi 
          image: eplast.azurecr.io/eplastapi
          ports:
          - containerPort: 5000
          env:
          - name: ConnectionStrings__EPlastDBConnection
            value: Server=tcp:eplast.database.windows.net,1433;Initial Catalog=EPlast;Persist Security Info=False;User ID=Admin_EPlast;Password=[rs6P<D7!akwQwb(;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
          - name: StorageConnectionString
            value: DefaultEndpointsProtocol=https;AccountName=eplaststorage;AccountKey=pjk94WswILGW7tJG+MgR9HeIxEaxlr1BEI8csIXrng5hK+ZJ6U6WoHIZfKomv85Yk2FUG8djRAmUjmWbAxs6GQ==;EndpointSuffix=core.windows.net
