apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: eplastapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eplastapi 
    spec:
      containers:
        - name: eplastapi 
          image: eplast.azurecr.io/eplastapi
          ports:
          - containerPort: 5000