apiVersion : apps/v1
kind: Deployment
metadata:
  name: eplastapi
  labels:
    app: eplastapi  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eplastapi
  template:
    metadata:
      labels:
        app: eplastapi 
    spec:
      containers:
        - name: eplastapi 
          image: ___containerRegistry___/eplastapi
          ports:
          - containerPort: 5000
          env:
          - name: ConnectionStrings__EPlastDBConnection
            value: ___ConnectionStrings__EPlastDBConnection___
          - name: StorageConnectionString
            value: ___StorageConnectionString___
          - name: EmailServiceSettings__SMTPServerLogin
            value: ___EmailServiceSettings__SMTPServerLogin___
          - name: EmailServiceSettings__SMTPServerPassword
            value: ___EmailServiceSettings__SMTPServerPassword___
          - name: Admin__Email
            value: ___Admin__Email___
          - name: Admin__Password
            value: ___Admin__Password___
            
            
